plugins {
    id 'java'
    id("xyz.jpenilla.run-paper") version "2.3.1"
}

group = 'com.mlc'
version = '1.0.0'

repositories {
    mavenCentral()
    maven {
        name = "papermc-repo"
        url = "https://repo.papermc.io/repository/maven-public/"
    }
    maven {
        name = "sonatype"
        url = "https://oss.sonatype.org/content/groups/public/"
    }
    maven {
        name = "Vault"
        url = "https://jitpack.io" }
}

dependencies {
    compileOnly("io.papermc.paper:paper-api:1.21.4-R0.1-SNAPSHOT")
    compileOnly("com.github.MilkBowl:VaultAPI:1.7"){
        exclude group: 'org.bukkit', module: 'bukkit'
    }
    implementation 'net.kyori:adventure-text-minimessage:4.13.0'
}

tasks {
  runServer {
    // Configure the Minecraft version for our task.
    // This is the only required configuration besides applying the plugin.
    // Your plugin's jar (or shadowJar if present) will be used automatically.
    minecraftVersion("1.21")
  }
}

def targetJavaVersion = 21
java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    sourceCompatibility = javaVersion
    targetCompatibility = javaVersion
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'

    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        options.release.set(targetJavaVersion)
    }
}

def versionpropsfile = file('version.properties')
def props = new Properties()
props.load(new FileInputStream(versionpropsfile))
def currentVersion = props['version'].toString()
def (versionMajor, versionMinor, versionPatch) = currentVersion.tokenize('.').collect { it.toInteger() }
def newVersion = "${versionMajor}.${versionMinor}.${versionPatch + 1}" as String
props['version'] = newVersion
props.store(versionpropsfile.newWriter(), null)
version = props['version']

processResources {
    inputs.property('version', version)
    filteringCharset 'UTF-8'
    filesMatching('plugin.yml') {
        expand version: version
    }
}
